numberOfErrors = 2

if numberOfErrors == 1:
    print("\t___________")
    print("\t|/        |")
    print("\t|         O")
    print("\t|")
    print("\t|")
    print("\t|")
    print("\t|__________")
if numberOfErrors == 2:
    print("\t___________")
    print("\t|/        |")
    print("\t|         O")
    print("\t|         |")
    print("\t|")
    print("\t|")
    print("\t|__________")
if numberOfErrors == 3:
    print("\t___________")
    print("\t|/        |")
    print("\t|         O")
    print("\t|        /|")
    print("\t|")
    print("\t|")
    print("\t|__________")
if numberOfErrors == 4:
    print("\t___________")
    print("\t|/        |")
    print("\t|         O")
    print("\t|        /|\\")
    print("\t|")
    print("\t|")
    print("\t|__________")
if numberOfErrors == 5:
    print("\t___________")
    print("\t|/        |")
    print("\t|         O")
    print("\t|        /|\\")
    print("\t|        / ")
    print("\t|")
    print("\t|__________")
if numberOfErrors == 6:
    print("\t___________")
    print("\t|/        |")
    print("\t|         O")
    print("\t|        /|\\")
    print("\t|        / \\")
    print("\t|")
    print("\t|__________")
